sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - env: TOX_ENV=py37
      python: 3.7
      dist: xenial
      sudo: true
      name: "Python 3.7 with Extensions"
    - env: TOX_ENV=py37-no-ext
      python: 3.7
      dist: xenial
      sudo: true
      name: "Python 3.7 without Extensions"
    - env: TOX_ENV=py38
      python: 3.8
      dist: xenial
      sudo: true
      name: "Python 3.8 with Extensions"
    - env: TOX_ENV=py38-no-ext
      python: 3.8
      dist: xenial
      sudo: true
      name: "Python 3.8 without Extensions"
    - env: TOX_ENV=py39
      python: 3.9
      dist: bionic
      sudo: true
      name: "Python 3.9 with Extensions"
    - env: TOX_ENV=py39-no-ext
      python: 3.9
      dist: bionic
      sudo: true
      name: "Python 3.9 without Extensions"
    - env: TOX_ENV=type-checking
      python: 3.7
      name: "Python 3.7 Type checks"
    - env: TOX_ENV=type-checking
      python: 3.8
      name: "Python 3.8 Type checks"
    - env: TOX_ENV=type-checking
      python: 3.9
      dist: bionic
      name: "Python 3.9 Type checks"
    - env: TOX_ENV=security
      python: 3.7
      dist: xenial
      sudo: true
      name: "Python 3.7 Bandit security scan"
    - env: TOX_ENV=security
      python: 3.8
      dist: xenial
      sudo: true
      name: "Python 3.8 Bandit security scan"
    - env: TOX_ENV=security
      python: 3.9
      dist: bionic
      sudo: true
      name: "Python 3.9 Bandit security scan"
    - env: TOX_ENV=docs
      python: 3.7
      dist: xenial
      sudo: true
      name: "Python 3.7 Documentation tests"
    - env: TOX_ENV=pyNightly
      python: "nightly"
      name: "Python nightly with Extensions"
    - env: TOX_ENV=pyNightly-no-ext
      python: "nightly"
      name: "Python nightly without Extensions"
  allow_failures:
    - env: TOX_ENV=pyNightly
      python: "nightly"
      name: "Python nightly with Extensions"
    - env: TOX_ENV=pyNightly-no-ext
      python: "nightly"
      name: "Python nightly without Extensions"
install:
  - pip install -U tox
  - pip install codecov
script: travis_retry tox -e $TOX_ENV
after_success:
  - codecov
deploy:
  provider: pypi
  user: brewmaster
  password:
    secure: "GoawLwmbtJOgKB6AJ0ZSYUUnNwIoonseHBxaAUH3zu79TS/Afrq+yB3lsVaMSG0CbyDgN4FrfD1phT1NzbvZ1VcLIOTDtCrmpQ1kLDw+zwgF40ab8sp8fPkKVHHHfCCs1mjltHIpxQa5lZTJcAs6Bpi/lbUWWwYxFzSV8pHw4W4hY09EHUd2o+evLTSVxaploetSt725DJUYKICUr2eAtCC11IDnIW4CzBJEx6krVV3uhzfTJW0Ls17x0c6sdZ9icMnV/G9xO/eQH6RIHe4xcrWJ6cmLDNKoGAkJp+BKr1CeVVg7Jw/MzPjvZKL2/ki6Beue1y6GUIy7lOS7jPVaOEhJ23b0zQwFcLMZw+Tt+E3v6QfHk+B/WBBBnM3zUZed9UI+QyW8+lqLLt39sQX0FO0P3eaDh8qTXtUuon2jTyFMMAMTFRTNpJmpAzuBH9yeMmDeALPTh0HphI+BkoUl5q1QbWFYjjnZMH2CatApxpLybt9A7rwm//PbOG0TSI93GEKNQ4w5DYryKTfwHzRBptNSephJSuxZYEfJsmUtas5es1D7Fe0PkyjxNNSU+eO+8wsTlitLUsJO4k0jAgy+cEKdU7YJ3J0GZVXocSkrNnUfd2hQPcJ3UtEJx3hLqqr8EM7EZBAasc1yGHh36NFetclzFY24YPih0G1+XurhTys="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
