name: py36
dependencies:
- pip=18.1=py36_0
- python=3.6=0
- setuptools=40.4.3=py36_0
- pip:
  - httptools>=0.0.10
  - uvloop>=0.5.3
  - ujson>=1.35
  - aiofiles>=0.3.0
  - websockets>=6.0,<7.0
  - multidict>=4.0,<5.0
  - sphinx==1.8.3
  - sphinx_rtd_theme==0.4.2
  - recommonmark==0.5.0
  - httpx==0.9.3
  - sphinxcontrib-asyncio>=0.2.0
  - docutils==0.14
  - pygments==2.3.1
