name: Run unit tests

on:
  pull_request:
    branches:
      - main
      - current-release
      - "*LTS"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run_linux_unit_tests:
    name: "Linux - ${{ matrix.config.tox-env }}"
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - { python-version: "3.8", tox-env: py38 }
          - { python-version: "3.8", tox-env: py38-no-ext }
          - { python-version: "3.9", tox-env: py39 }
          - { python-version: "3.9", tox-env: py39-no-ext }
          - { python-version: "3.10", tox-env: py310 }
          - { python-version: "3.10", tox-env: py310-no-ext }
          - { python-version: "3.11", tox-env: py311 }
          - { python-version: "3.11", tox-env: py311-no-ext }
    steps:
      - name: Run unit tests
        uses: prryplatypus/simple-tox@main
        with:
          python-version: ${{ matrix.config.python-version }}
          tox-env: ${{ matrix.config.tox-env }}
          max-attempts: 3

  run_windows_unit_tests:
    name: "Windows - ${{ matrix.config.tox-env }}"
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - { python-version: "3.8", tox-env: py38-no-ext }
          - { python-version: "3.9", tox-env: py39-no-ext }
          - { python-version: "3.10", tox-env: py310-no-ext }
          - { python-version: "3.11", tox-env: py310-no-ext }
    continue-on-error: true
    steps:
      - name: Run unit tests
        id: run-unit-tests
        uses: prryplatypus/simple-tox@main
        with:
          python-version: ${{ matrix.config.python-version }}
          tox-env: ${{ matrix.config.tox-env }}

      - name: Output warning if failed
        if: steps.run-unit-tests.outcome == 'failure'
        run: Write-Host "::warning::Unit tests failed, but exiting with success code"
